In [2]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [5]:
data = load_iris()
X, y, column_names = data['data'], data['target'], data['feature_names']
X = pd.DataFrame(X, columns = column_names)
X['target'] = y

In [6]:
X

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [32]:

def bootstrap(df, nboot):
    idx = np.random.randint(df.shape[0], size = (nboot, df.shape[0]))
    idx_flat = np.ravel(idx)
    
    return df.iloc[idx_flat, :]

bootstappedDF = bootstrap(X, 100)

In [33]:
bootstappedDF

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
89,5.5,2.5,4.0,1.3,1
16,5.4,3.9,1.3,0.4,0
33,5.5,4.2,1.4,0.2,0
20,5.4,3.4,1.7,0.2,0
140,6.7,3.1,5.6,2.4,2
...,...,...,...,...,...
87,6.3,2.3,4.4,1.3,1
149,5.9,3.0,5.1,1.8,2
63,6.1,2.9,4.7,1.4,1
12,4.8,3.0,1.4,0.1,0
104,6.5,3.0,5.8,2.2,2

In [35]:
bootstappedDF["target"].values

array([1, 0, 0, ..., 1, 0, 2])

In [ ]:
def getImpurity(y, target_class_list):
    for one_class in target_class_list: 
        t[]

def calcBestSplit(self, X, y):
        '''
        Calculates the best possible split for the concrete node of the tree
        '''
        
        bestSplitCol = None
        bestThresh = None
        bestInfoGain = -999
        
        # 나누기 전 현재의 데이터 분포에서 impurity 를 계산한다. 
        impurityBefore = self.calcImpurity(y)
        
        # X는 2차원의 table 데이터 이므로, (행 수, 열 수) 의 shape을 갖는다. 
        # 따라서, 모든 variable 들에 대해서 info gain을 계산해야 하므로 loop 돌린다. 
        for col in range(X.shape[1]):
            x_col = X[:, col]  # 행은 전부다, 열은 col으로 지정한 열만. 
            
            # 각각의 모든 value 들을 기준로 나눈다. 
            for x_i in x_col:
                threshold = x_i
                y_right = y[x_col > threshold]
                y_left = y[x_col <= threshold]
                
                if y_right.shape[0] == 0 or y_left.shape[0] == 0:
                    continue
                    
                # calculate impurity for the right and left nodes
                impurityRight = self.calcImpurity(y_right)
                impurityLeft = self.calcImpurity(y_left)
                
                # calculate information gain
                infoGain = impurityBefore
                infoGain -= (impurityLeft * y_left.shape[0] / y.shape[0]) + (impurityRight * y_right.shape[0] / y.shape[0])
                
                # is this infoGain better then all other?
                if infoGain > bestInfoGain:
                    bestSplitCol = col
                    bestThresh = threshold
                    bestInfoGain = infoGain
                    
        
        # if we still didn't find the split
        if bestInfoGain == -999:
            return None, None, None, None, None, None
        
        # making the best split
        
        x_col = X[:, bestSplitCol]
        x_left, x_right = X[x_col <= bestThresh, :], X[x_col > bestThresh, :]
        y_left, y_right = y[x_col <= bestThresh], y[x_col > bestThresh]
        
        return bestSplitCol, bestThresh, x_left, y_left, x_right, y_right